Fix appraisals and issue for guest users
vinsol-spree-contrib/promotion_multi_coupon pull request #26
Opened 2018-04-08 10:16 UTC by harsh-ag

2018-04-30 08:38 UTC, sawangupta92 requested changes

2018-04-30 08:38 UTC, sawangupta92 commented on app/models/spree/order_decorator.rb
> +    def create_line_item_promotion
doesn't seems right to me

2018-04-30 08:38 UTC, sawangupta92 commented on app/models/spree/order_decorator.rb
> +      promotions.joins(:promotion_actions).where(spree_promotion_actions: { type: 'Spree::Promotion::Actions::CreateLineItems' }).last
why are we only marking it true for Spree::Promotion::Actions::CreateLineItems?

2018-04-30 08:38 UTC, sawangupta92 commented on app/models/spree/order_decorator.rb
> +    promotion = promotions.where(id: promotion_ids).where(multi_coupon: true).last
can be replaced with?

promotions.find_by(id: promotion_ids, multi_coupon: true)

2018-04-30 08:38 UTC, sawangupta92 commented on app/models/spree/promotion_decorator.rb
> +      if coupon_code.blank? || codes.where("user_id = ? AND lower(code) = ?", promotable_user.try(:id), coupon_code).exists?
was this giving exception?

2018-04-30 08:38 UTC, sawangupta92 commented on app/models/spree/order_decorator.rb
> +  def update_multi_coupon_codes
make sure that this one get tested properly.

2018-05-03 06:53 UTC, harsh-ag commented on app/models/spree/promotion_decorator.rb
> +      if coupon_code.blank? || codes.where("user_id = ? AND lower(code) = ?", promotable_user.try(:id), coupon_code).exists?
this was done for guest users.

2018-05-08 17:59 UTC, sawangupta92 approved these changes

2018-05-10 06:07 UTC, merged